---

- name: Copiar o repositorio oficial do nginx para o servidor
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Atualizacao do sistema operacional
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

# - name: Instalacao dos pacotes nginx
#   yum:
#     name: ['nginx.x86_64', 'nginx-module-geoip-1.16.1-1.el7.ngx.x86_64.rpm']
#     state: latest
#   when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

# - name: Criar copia de seguranca do dest=/etc/nginx
#   command: mv /etc/nginx /etc/nginx_original
#   args:
#     warn: false
#   when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Copiar o nginx.tar.gz para o servidor
  unarchive:
    src: nginx.tar.gz
    dest: /etc/
    owner: root
    group: root
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Criacao de diretorios do nginx
  file: path={{item}} state=directory
  with_items:
    - /var/www
    - /var/www/html
  notify: Restart nginx
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
...