---

- name: Restart php-fpm
  systemd: 
    name: php-fpm 
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  # systemd:
  #   state: restarted
  #   daemon_reload: yes
  #   name: nginx
    
    

...